/**
 * マネキャラ診断ロジック
 * 15問の質問から、ユーザーのお金の性格タイプを判定
 */

export interface DiagnosisQuestion {
  id: string;
  text: string;
  answers: {
    text: string;
    scores: Record<string, number>; // キャラクターIDごとのスコア
  }[];
}

export const DIAGNOSIS_QUESTIONS: DiagnosisQuestion[] = [
  {
    id: "q1",
    text: "欲しいものを見つけたとき、あなたはどうする？",
    answers: [
      {
        text: "すぐに買う。後悔は後で考える。",
        scores: {
          spender: 3,
          miser: 0,
          pointCollector: 1,
          saver: 0,
          investor: 0,
          vain: 2,
          procrastinator: 1,
          gambler: 2,
          frog: 0,
          lion: 1,
          swan: 1,
          rabbit: 2,
        },
      },
      {
        text: "1週間考えてから買うか決める。",
        scores: {
          spender: 1,
          miser: 1,
          pointCollector: 2,
          saver: 2,
          investor: 2,
          vain: 1,
          procrastinator: 0,
          gambler: 0,
          frog: 1,
          lion: 0,
          swan: 3,
          rabbit: 1,
        },
      },
      {
        text: "本当に必要か、何度も考える。",
        scores: {
          spender: 0,
          miser: 3,
          pointCollector: 1,
          saver: 2,
          investor: 1,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 2,
          lion: 0,
          swan: 1,
          rabbit: 0,
        },
      },
      {
        text: "セールやポイント還元を確認してから買う。",
        scores: {
          spender: 0,
          miser: 1,
          pointCollector: 3,
          saver: 1,
          investor: 0,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 0,
          lion: 0,
          swan: 0,
          rabbit: 3,
        },
      },
    ],
  },
  {
    id: "q2",
    text: "給料日、あなたはまず何をする？",
    answers: [
      {
        text: "友達と食事に行く。お金は使ってナンボ。",
        scores: {
          spender: 2,
          miser: 0,
          pointCollector: 0,
          saver: 0,
          investor: 0,
          vain: 1,
          procrastinator: 1,
          gambler: 1,
          frog: 0,
          lion: 3,
          swan: 1,
          rabbit: 0,
        },
      },
      {
        text: "貯金に回す額を決めて、残りで生活する。",
        scores: {
          spender: 0,
          miser: 2,
          pointCollector: 1,
          saver: 3,
          investor: 2,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 1,
          lion: 0,
          swan: 2,
          rabbit: 0,
        },
      },
      {
        text: "投資に回す。複利の力を信じてる。",
        scores: {
          spender: 0,
          miser: 0,
          pointCollector: 0,
          saver: 1,
          investor: 3,
          vain: 0,
          procrastinator: 0,
          gambler: 2,
          frog: 0,
          lion: 0,
          swan: 0,
          rabbit: 0,
        },
      },
      {
        text: "ブランド品や高級品を買う。自分へのご褒美。",
        scores: {
          spender: 1,
          miser: 0,
          pointCollector: 0,
          saver: 0,
          investor: 0,
          vain: 3,
          procrastinator: 0,
          gambler: 1,
          frog: 0,
          lion: 0,
          swan: 2,
          rabbit: 0,
        },
      },
    ],
  },
  {
    id: "q3",
    text: "家計簿をつけていますか？",
    answers: [
      {
        text: "毎日つけてる。家計管理は人生管理。",
        scores: {
          spender: 0,
          miser: 3,
          pointCollector: 2,
          saver: 3,
          investor: 2,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 2,
          lion: 0,
          swan: 1,
          rabbit: 0,
        },
      },
      {
        text: "月1回くらい確認する。",
        scores: {
          spender: 0,
          miser: 1,
          pointCollector: 1,
          saver: 2,
          investor: 2,
          vain: 0,
          procrastinator: 1,
          gambler: 1,
          frog: 1,
          lion: 0,
          swan: 2,
          rabbit: 1,
        },
      },
      {
        text: "つけてない。面倒くさい。",
        scores: {
          spender: 2,
          miser: 0,
          pointCollector: 0,
          saver: 0,
          investor: 0,
          vain: 1,
          procrastinator: 3,
          gambler: 1,
          frog: 0,
          lion: 1,
          swan: 0,
          rabbit: 1,
        },
      },
      {
        text: "アプリで自動管理している。",
        scores: {
          spender: 0,
          miser: 1,
          pointCollector: 2,
          saver: 2,
          investor: 3,
          vain: 0,
          procrastinator: 1,
          gambler: 0,
          frog: 1,
          lion: 0,
          swan: 1,
          rabbit: 1,
        },
      },
    ],
  },
  {
    id: "q4",
    text: "セール・キャンペーン情報を見ると？",
    answers: [
      {
        text: "すぐに行く。安いチャンスは逃せない。",
        scores: {
          spender: 2,
          miser: 0,
          pointCollector: 1,
          saver: 0,
          investor: 0,
          vain: 1,
          procrastinator: 0,
          gambler: 1,
          frog: 0,
          lion: 0,
          swan: 0,
          rabbit: 3,
        },
      },
      {
        text: "本当に必要なら行く。",
        scores: {
          spender: 0,
          miser: 2,
          pointCollector: 2,
          saver: 2,
          investor: 1,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 1,
          lion: 0,
          swan: 2,
          rabbit: 1,
        },
      },
      {
        text: "ポイント還元を確認してから。",
        scores: {
          spender: 0,
          miser: 0,
          pointCollector: 3,
          saver: 1,
          investor: 0,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 0,
          lion: 0,
          swan: 0,
          rabbit: 2,
        },
      },
      {
        text: "見ない。セール情報は避けてる。",
        scores: {
          spender: 0,
          miser: 1,
          pointCollector: 0,
          saver: 2,
          investor: 2,
          vain: 0,
          procrastinator: 1,
          gambler: 0,
          frog: 1,
          lion: 0,
          swan: 1,
          rabbit: 0,
        },
      },
    ],
  },
  {
    id: "q5",
    text: "友達との食事代、どうしてる？",
    answers: [
      {
        text: "割り勘。1円の誤差も許さない。",
        scores: {
          spender: 0,
          miser: 1,
          pointCollector: 1,
          saver: 0,
          investor: 0,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 3,
          lion: 0,
          swan: 0,
          rabbit: 0,
        },
      },
      {
        text: "気分で奢ったり、奢られたり。",
        scores: {
          spender: 2,
          miser: 0,
          pointCollector: 0,
          saver: 0,
          investor: 0,
          vain: 1,
          procrastinator: 1,
          gambler: 1,
          frog: 1,
          lion: 2,
          swan: 1,
          rabbit: 0,
        },
      },
      {
        text: "いつも奢る側。友人のためなら。",
        scores: {
          spender: 1,
          miser: 0,
          pointCollector: 0,
          saver: 0,
          investor: 0,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 0,
          lion: 3,
          swan: 1,
          rabbit: 0,
        },
      },
      {
        text: "割り勘だけど、ポイント還元を考慮。",
        scores: {
          spender: 0,
          miser: 0,
          pointCollector: 2,
          saver: 1,
          investor: 0,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 2,
          lion: 0,
          swan: 0,
          rabbit: 1,
        },
      },
    ],
  },
  {
    id: "q6",
    text: "貯金通帳を見ると？",
    answers: [
      {
        text: "不安になる。もっと貯めなきゃ。",
        scores: {
          spender: 0,
          miser: 3,
          pointCollector: 1,
          saver: 2,
          investor: 1,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 1,
          lion: 0,
          swan: 1,
          rabbit: 0,
        },
      },
      {
        text: "安心する。これだけあれば大丈夫。",
        scores: {
          spender: 0,
          miser: 2,
          pointCollector: 0,
          saver: 2,
          investor: 0,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 0,
          lion: 0,
          swan: 1,
          rabbit: 0,
        },
      },
      {
        text: "投資に回したい。複利で増やしたい。",
        scores: {
          spender: 0,
          miser: 0,
          pointCollector: 0,
          saver: 1,
          investor: 3,
          vain: 0,
          procrastinator: 0,
          gambler: 2,
          frog: 0,
          lion: 0,
          swan: 0,
          rabbit: 0,
        },
      },
      {
        text: "見たくない。見ると落ち込む。",
        scores: {
          spender: 2,
          miser: 0,
          pointCollector: 0,
          saver: 0,
          investor: 0,
          vain: 1,
          procrastinator: 2,
          gambler: 1,
          frog: 0,
          lion: 1,
          swan: 0,
          rabbit: 1,
        },
      },
    ],
  },
  {
    id: "q7",
    text: "投資に興味がありますか？",
    answers: [
      {
        text: "大好き。株、投信、仮想通貨など試してる。",
        scores: {
          spender: 0,
          miser: 0,
          pointCollector: 0,
          saver: 1,
          investor: 3,
          vain: 0,
          procrastinator: 0,
          gambler: 2,
          frog: 0,
          lion: 0,
          swan: 0,
          rabbit: 0,
        },
      },
      {
        text: "興味あるけど、怖い。",
        scores: {
          spender: 0,
          miser: 2,
          pointCollector: 1,
          saver: 2,
          investor: 0,
          vain: 0,
          procrastinator: 1,
          gambler: 0,
          frog: 1,
          lion: 0,
          swan: 1,
          rabbit: 0,
        },
      },
      {
        text: "興味ない。貯金で十分。",
        scores: {
          spender: 0,
          miser: 2,
          pointCollector: 0,
          saver: 1,
          investor: 0,
          vain: 0,
          procrastinator: 1,
          gambler: 0,
          frog: 1,
          lion: 0,
          swan: 0,
          rabbit: 0,
        },
      },
      {
        text: "ポイント投資から始めたい。",
        scores: {
          spender: 0,
          miser: 0,
          pointCollector: 3,
          saver: 1,
          investor: 1,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 0,
          lion: 0,
          swan: 0,
          rabbit: 1,
        },
      },
    ],
  },
  {
    id: "q8",
    text: "ポイントやクーポンを集めるのは？",
    answers: [
      {
        text: "大好き。失効させたら悔しい。",
        scores: {
          spender: 0,
          miser: 1,
          pointCollector: 3,
          saver: 1,
          investor: 0,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 1,
          lion: 0,
          swan: 0,
          rabbit: 2,
        },
      },
      {
        text: "まあ、集まったら使う程度。",
        scores: {
          spender: 1,
          miser: 0,
          pointCollector: 1,
          saver: 1,
          investor: 0,
          vain: 0,
          procrastinator: 1,
          gambler: 0,
          frog: 0,
          lion: 0,
          swan: 1,
          rabbit: 1,
        },
      },
      {
        text: "興味ない。複雑で面倒。",
        scores: {
          spender: 1,
          miser: 1,
          pointCollector: 0,
          saver: 0,
          investor: 1,
          vain: 1,
          procrastinator: 2,
          gambler: 1,
          frog: 0,
          lion: 1,
          swan: 0,
          rabbit: 0,
        },
      },
      {
        text: "効率的に使う。最大限の還元を狙う。",
        scores: {
          spender: 0,
          miser: 1,
          pointCollector: 2,
          saver: 2,
          investor: 1,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 1,
          lion: 0,
          swan: 0,
          rabbit: 1,
        },
      },
    ],
  },
  {
    id: "q9",
    text: "ブランド品や高級品への興味は？",
    answers: [
      {
        text: "大好き。質の良いものに囲まれたい。",
        scores: {
          spender: 1,
          miser: 0,
          pointCollector: 0,
          saver: 0,
          investor: 0,
          vain: 3,
          procrastinator: 0,
          gambler: 0,
          frog: 0,
          lion: 0,
          swan: 2,
          rabbit: 0,
        },
      },
      {
        text: "時々買う。自分へのご褒美として。",
        scores: {
          spender: 1,
          miser: 0,
          pointCollector: 0,
          saver: 0,
          investor: 0,
          vain: 1,
          procrastinator: 0,
          gambler: 0,
          frog: 0,
          lion: 0,
          swan: 3,
          rabbit: 0,
        },
      },
      {
        text: "興味ない。安くて質が良ければOK。",
        scores: {
          spender: 0,
          miser: 2,
          pointCollector: 1,
          saver: 2,
          investor: 1,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 1,
          lion: 0,
          swan: 0,
          rabbit: 1,
        },
      },
      {
        text: "セール品なら買う。",
        scores: {
          spender: 1,
          miser: 0,
          pointCollector: 1,
          saver: 0,
          investor: 0,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 0,
          lion: 0,
          swan: 0,
          rabbit: 2,
        },
      },
    ],
  },
  {
    id: "q10",
    text: "将来のお金について、どう考えてる？",
    answers: [
      {
        text: "今を楽しむ。将来は何とかなる。",
        scores: {
          spender: 2,
          miser: 0,
          pointCollector: 0,
          saver: 0,
          investor: 0,
          vain: 1,
          procrastinator: 2,
          gambler: 1,
          frog: 0,
          lion: 1,
          swan: 0,
          rabbit: 0,
        },
      },
      {
        text: "計画的に貯金・投資してる。",
        scores: {
          spender: 0,
          miser: 2,
          pointCollector: 1,
          saver: 3,
          investor: 2,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 1,
          lion: 0,
          swan: 1,
          rabbit: 0,
        },
      },
      {
        text: "大きなリターンを狙ってる。",
        scores: {
          spender: 0,
          miser: 0,
          pointCollector: 0,
          saver: 0,
          investor: 2,
          vain: 0,
          procrastinator: 0,
          gambler: 3,
          frog: 0,
          lion: 0,
          swan: 0,
          rabbit: 0,
        },
      },
      {
        text: "不安。何をしたらいいかわからない。",
        scores: {
          spender: 1,
          miser: 1,
          pointCollector: 0,
          saver: 0,
          investor: 0,
          vain: 0,
          procrastinator: 3,
          gambler: 0,
          frog: 0,
          lion: 0,
          swan: 0,
          rabbit: 0,
        },
      },
    ],
  },
  {
    id: "q11",
    text: "月の貯金目標は？",
    answers: [
      {
        text: "決めてない。余ったら貯金する。",
        scores: {
          spender: 2,
          miser: 0,
          pointCollector: 0,
          saver: 0,
          investor: 0,
          vain: 1,
          procrastinator: 2,
          gambler: 1,
          frog: 0,
          lion: 1,
          swan: 0,
          rabbit: 1,
        },
      },
      {
        text: "給料の10-20%は貯金。",
        scores: {
          spender: 0,
          miser: 1,
          pointCollector: 1,
          saver: 2,
          investor: 1,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 1,
          lion: 0,
          swan: 1,
          rabbit: 0,
        },
      },
      {
        text: "給料の30%以上は貯金・投資。",
        scores: {
          spender: 0,
          miser: 2,
          pointCollector: 0,
          saver: 3,
          investor: 3,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 0,
          lion: 0,
          swan: 1,
          rabbit: 0,
        },
      },
      {
        text: "目標は決めてるけど、達成できない。",
        scores: {
          spender: 1,
          miser: 0,
          pointCollector: 0,
          saver: 0,
          investor: 0,
          vain: 0,
          procrastinator: 2,
          gambler: 0,
          frog: 0,
          lion: 0,
          swan: 0,
          rabbit: 0,
        },
      },
    ],
  },
  {
    id: "q12",
    text: "家計管理で大切なことは？",
    answers: [
      {
        text: "人間関係。友人との付き合いが最優先。",
        scores: {
          spender: 1,
          miser: 0,
          pointCollector: 0,
          saver: 0,
          investor: 0,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 0,
          lion: 3,
          swan: 0,
          rabbit: 0,
        },
      },
      {
        text: "メリハリ。節約と贅沢のバランス。",
        scores: {
          spender: 0,
          miser: 0,
          pointCollector: 1,
          saver: 1,
          investor: 1,
          vain: 1,
          procrastinator: 0,
          gambler: 0,
          frog: 1,
          lion: 0,
          swan: 3,
          rabbit: 1,
        },
      },
      {
        text: "効率。最小限の手間で最大限の成果。",
        scores: {
          spender: 0,
          miser: 1,
          pointCollector: 2,
          saver: 2,
          investor: 2,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 1,
          lion: 0,
          swan: 0,
          rabbit: 1,
        },
      },
      {
        text: "完璧さ。1円の誤差も許さない。",
        scores: {
          spender: 0,
          miser: 3,
          pointCollector: 1,
          saver: 2,
          investor: 1,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 2,
          lion: 0,
          swan: 0,
          rabbit: 0,
        },
      },
    ],
  },
  {
    id: "q13",
    text: "お金で失敗したことは？",
    answers: [
      {
        text: "衝動買いで後悔。",
        scores: {
          spender: 3,
          miser: 0,
          pointCollector: 1,
          saver: 0,
          investor: 0,
          vain: 2,
          procrastinator: 0,
          gambler: 0,
          frog: 0,
          lion: 0,
          swan: 0,
          rabbit: 2,
        },
      },
      {
        text: "投資で損失。",
        scores: {
          spender: 0,
          miser: 0,
          pointCollector: 0,
          saver: 0,
          investor: 1,
          vain: 0,
          procrastinator: 0,
          gambler: 3,
          frog: 0,
          lion: 0,
          swan: 0,
          rabbit: 0,
        },
      },
      {
        text: "友人にお金を貸して返ってこない。",
        scores: {
          spender: 0,
          miser: 0,
          pointCollector: 0,
          saver: 0,
          investor: 0,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 1,
          lion: 2,
          swan: 0,
          rabbit: 0,
        },
      },
      {
        text: "特に失敗していない。",
        scores: {
          spender: 0,
          miser: 2,
          pointCollector: 1,
          saver: 2,
          investor: 2,
          vain: 0,
          procrastinator: 1,
          gambler: 0,
          frog: 1,
          lion: 0,
          swan: 1,
          rabbit: 0,
        },
      },
    ],
  },
  {
    id: "q14",
    text: "新しい家計管理方法を試すなら？",
    answers: [
      {
        text: "すぐに試す。新しいことが好き。",
        scores: {
          spender: 1,
          miser: 0,
          pointCollector: 2,
          saver: 0,
          investor: 2,
          vain: 1,
          procrastinator: 0,
          gambler: 1,
          frog: 0,
          lion: 0,
          swan: 1,
          rabbit: 1,
        },
      },
      {
        text: "効果を確認してから試す。",
        scores: {
          spender: 0,
          miser: 2,
          pointCollector: 1,
          saver: 2,
          investor: 2,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 1,
          lion: 0,
          swan: 1,
          rabbit: 0,
        },
      },
      {
        text: "今のやり方で十分。変える必要ない。",
        scores: {
          spender: 0,
          miser: 1,
          pointCollector: 0,
          saver: 1,
          investor: 0,
          vain: 0,
          procrastinator: 2,
          gambler: 0,
          frog: 1,
          lion: 0,
          swan: 0,
          rabbit: 0,
        },
      },
      {
        text: "興味あるけど、後でいいや。",
        scores: {
          spender: 1,
          miser: 0,
          pointCollector: 0,
          saver: 0,
          investor: 0,
          vain: 0,
          procrastinator: 3,
          gambler: 0,
          frog: 0,
          lion: 0,
          swan: 0,
          rabbit: 0,
        },
      },
    ],
  },
  {
    id: "q15",
    text: "理想の人生は？",
    answers: [
      {
        text: "今を楽しむ。人生は一度きり。",
        scores: {
          spender: 2,
          miser: 0,
          pointCollector: 0,
          saver: 0,
          investor: 0,
          vain: 2,
          procrastinator: 1,
          gambler: 1,
          frog: 0,
          lion: 2,
          swan: 1,
          rabbit: 0,
        },
      },
      {
        text: "安定した生活。貯金がたくさんあると安心。",
        scores: {
          spender: 0,
          miser: 3,
          pointCollector: 1,
          saver: 3,
          investor: 1,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 1,
          lion: 0,
          swan: 1,
          rabbit: 0,
        },
      },
      {
        text: "自由な生活。お金に困らない生活。",
        scores: {
          spender: 0,
          miser: 1,
          pointCollector: 1,
          saver: 1,
          investor: 3,
          vain: 0,
          procrastinator: 0,
          gambler: 2,
          frog: 0,
          lion: 0,
          swan: 0,
          rabbit: 0,
        },
      },
      {
        text: "人間関係を大切にした生活。",
        scores: {
          spender: 1,
          miser: 0,
          pointCollector: 0,
          saver: 0,
          investor: 0,
          vain: 0,
          procrastinator: 0,
          gambler: 0,
          frog: 2,
          lion: 3,
          swan: 0,
          rabbit: 0,
        },
      },
    ],
  },
];

export interface DiagnosisResult {
  characterId: string;
  score: number;
  allScores: Record<string, number>;
}

export function calculateDiagnosis(answers: string[]): DiagnosisResult {
  // 各キャラクターのスコアを初期化
  const scores: Record<string, number> = {
    spender: 0,
    miser: 0,
    pointCollector: 0,
    saver: 0,
    investor: 0,
    vain: 0,
    procrastinator: 0,
    gambler: 0,
    frog: 0,
    lion: 0,
    swan: 0,
    rabbit: 0,
  };

  // 各質問の回答からスコアを加算
  answers.forEach((answerIndex, questionIndex) => {
    const question = DIAGNOSIS_QUESTIONS[questionIndex];
    const answerIdx = parseInt(answerIndex);
    const answer = question.answers[answerIdx];

    Object.keys(answer.scores).forEach((characterId) => {
      scores[characterId] += answer.scores[characterId];
    });
  });

  // 最高スコアのキャラクターを取得
  let maxScore = 0;
  let characterId = "spender";

  Object.entries(scores).forEach(([id, score]) => {
    if (score > maxScore) {
      maxScore = score;
      characterId = id;
    }
  });

  return {
    characterId,
    score: maxScore,
    allScores: scores,
  };
}
